spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # you are expected this three lines with host, DB name, username and password
    url: jdbc:postgresql://localhost:5432/moneytransferdb
    username: mt
    password: mt2021
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090